### ISSUE TITLE
File Upload (Chunk) SDK Code

### ISSUE THREAD

**Issue by radians-theta** [solvexia/solvexia-python-sdk#1]
### File Upload (Chunk) SDK Code

Some items that need to be generalised

* The Code has undefined variables 'Env', 'Hload'
* Hard-coded URL that is pointing to QA Servers; this means a genuine client won't be able to use the function.
* File names are hard-coded.

![image](https://user-images.githubusercontent.com/28833249/93156600-c781c580-f74b-11ea-90f4-a4c056d90af1.png)

**Comment by myfoxtail** [comment]
@cadlag-rcll thanks for the issue. This will be fixed by introducing the __init__ method in `solvexia_client` class. I'm planning to push it soon.

**Comment by myfoxtail** [comment]
I believe this has been resolved in previous versions. I'm closing the ticket now. Please feel free to open again if required.
